//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BibliothequeUser.BibliothequeService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BibliothequeSoap", Namespace="http://stardis.blue/")]
    public partial class Bibliotheque : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBookOperationCompleted;
        
        private System.Threading.SendOrPostCallback findBooksOperationCompleted;
        
        private System.Threading.SendOrPostCallback findBooksByAuthorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Bibliotheque() {
            this.Url = global::BibliothequeUser.Properties.Settings.Default.BibliothequeUser_BibliothequeService_Bibliotheque;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getBooksCompletedEventHandler getBooksCompleted;
        
        /// <remarks/>
        public event getBookCompletedEventHandler getBookCompleted;
        
        /// <remarks/>
        public event findBooksCompletedEventHandler findBooksCompleted;
        
        /// <remarks/>
        public event findBooksByAuthorCompletedEventHandler findBooksByAuthorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stardis.blue/getBooks", RequestNamespace="http://stardis.blue/", ResponseNamespace="http://stardis.blue/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Book[] getBooks() {
            object[] results = this.Invoke("getBooks", new object[0]);
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void getBooksAsync() {
            this.getBooksAsync(null);
        }
        
        /// <remarks/>
        public void getBooksAsync(object userState) {
            if ((this.getBooksOperationCompleted == null)) {
                this.getBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBooksOperationCompleted);
            }
            this.InvokeAsync("getBooks", new object[0], this.getBooksOperationCompleted, userState);
        }
        
        private void OngetBooksOperationCompleted(object arg) {
            if ((this.getBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBooksCompleted(this, new getBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stardis.blue/getBook", RequestNamespace="http://stardis.blue/", ResponseNamespace="http://stardis.blue/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Book getBook(int ISBN) {
            object[] results = this.Invoke("getBook", new object[] {
                        ISBN});
            return ((Book)(results[0]));
        }
        
        /// <remarks/>
        public void getBookAsync(int ISBN) {
            this.getBookAsync(ISBN, null);
        }
        
        /// <remarks/>
        public void getBookAsync(int ISBN, object userState) {
            if ((this.getBookOperationCompleted == null)) {
                this.getBookOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBookOperationCompleted);
            }
            this.InvokeAsync("getBook", new object[] {
                        ISBN}, this.getBookOperationCompleted, userState);
        }
        
        private void OngetBookOperationCompleted(object arg) {
            if ((this.getBookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBookCompleted(this, new getBookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stardis.blue/findBooks", RequestNamespace="http://stardis.blue/", ResponseNamespace="http://stardis.blue/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Book[] findBooks(string name) {
            object[] results = this.Invoke("findBooks", new object[] {
                        name});
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void findBooksAsync(string name) {
            this.findBooksAsync(name, null);
        }
        
        /// <remarks/>
        public void findBooksAsync(string name, object userState) {
            if ((this.findBooksOperationCompleted == null)) {
                this.findBooksOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindBooksOperationCompleted);
            }
            this.InvokeAsync("findBooks", new object[] {
                        name}, this.findBooksOperationCompleted, userState);
        }
        
        private void OnfindBooksOperationCompleted(object arg) {
            if ((this.findBooksCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findBooksCompleted(this, new findBooksCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://stardis.blue/findBooksByAuthor", RequestNamespace="http://stardis.blue/", ResponseNamespace="http://stardis.blue/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Book[] findBooksByAuthor(string FirstName, string LastName) {
            object[] results = this.Invoke("findBooksByAuthor", new object[] {
                        FirstName,
                        LastName});
            return ((Book[])(results[0]));
        }
        
        /// <remarks/>
        public void findBooksByAuthorAsync(string FirstName, string LastName) {
            this.findBooksByAuthorAsync(FirstName, LastName, null);
        }
        
        /// <remarks/>
        public void findBooksByAuthorAsync(string FirstName, string LastName, object userState) {
            if ((this.findBooksByAuthorOperationCompleted == null)) {
                this.findBooksByAuthorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindBooksByAuthorOperationCompleted);
            }
            this.InvokeAsync("findBooksByAuthor", new object[] {
                        FirstName,
                        LastName}, this.findBooksByAuthorOperationCompleted, userState);
        }
        
        private void OnfindBooksByAuthorOperationCompleted(object arg) {
            if ((this.findBooksByAuthorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findBooksByAuthorCompleted(this, new findBooksByAuthorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stardis.blue/")]
    public partial class Book {
        
        private int iSBNField;
        
        private Author authorField;
        
        private string titleField;
        
        private string descriptionField;
        
        private string genreField;
        
        private System.DateTime datePublicationField;
        
        /// <remarks/>
        public int ISBN {
            get {
                return this.iSBNField;
            }
            set {
                this.iSBNField = value;
            }
        }
        
        /// <remarks/>
        public Author Author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Genre {
            get {
                return this.genreField;
            }
            set {
                this.genreField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DatePublication {
            get {
                return this.datePublicationField;
            }
            set {
                this.datePublicationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stardis.blue/")]
    public partial class Author {
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.DateTime dateOfBirthField;
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateOfBirth {
            get {
                return this.dateOfBirthField;
            }
            set {
                this.dateOfBirthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getBooksCompletedEventHandler(object sender, getBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void getBookCompletedEventHandler(object sender, getBookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void findBooksCompletedEventHandler(object sender, findBooksCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findBooksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findBooksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void findBooksByAuthorCompletedEventHandler(object sender, findBooksByAuthorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findBooksByAuthorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findBooksByAuthorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Book[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Book[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591